dist: bionic
sudo: false
addons:
  apt:
    packages:
      - python3-pytest
      - jq
before_script:
  - |
    pushd /tmp
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_linux_amd64.deb
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_checksums.txt
    sha256sum -c --ignore-missing task_checksums.txt
    sudo dpkg -i task_linux_amd64.deb
    popd
after_success:
  - docker image ls
script:
  - task build
  - task tests
