os: linux
dist: bionic
language: python
python:
  - "3.8.3"
install:
  - pip install -U pip
  - pip install pytest
before_script:
  - |
    pushd /tmp && \
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_linux_amd64.deb && \
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_checksums.txt && \
    sha256sum -c --ignore-missing task_checksums.txt && \
    sudo dpkg -i task_linux_amd64.deb && \
    popd

env:
  matrix:
    - IMAGE_NAME=ubuntu-16.04
    - IMAGE_NAME=ubuntu-18.04
    - IMAGE_NAME=ubuntu-20.04
    - IMAGE_NAME=fedora-29
    - IMAGE_NAME=fedora-30

script:
  - task tests IMAGES=$IMAGE_NAME

# Only run release on release branch
after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ] || [ "$TRAVIS_BRANCH" == "test-release" ]; then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; task release IMAGES=$IMAGE_NAME; fi || exit 1
