os: linux
dist: bionic
language: python
python:
  - '3.8'
addons:
  apt:
    packages:
      - jq
install:
  - pip install -U pip
  - pip install pytest
before_script:
  - |
    pushd /tmp && \
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_linux_amd64.deb && \
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_checksums.txt && \
    sha256sum -c --ignore-missing task_checksums.txt && \
    sudo dpkg -i task_linux_amd64.deb && \
    popd
jobs:
  include:
    - stage: "CI"
      name: "Build and unit test"
      script:
        - task build
        - task tests
# Only run release on release branch
after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then task release; fi
