dist: bionic
sudo: false
addons:
  apt:
    packages:
      - python3-pytest
      - jq
      - coreutils
before_install:
  - |
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_linux_amd64.deb
    https://github.com/go-task/task/releases/download/v2.8.0/task_checksums.txt
    sha256sums -C task_checksums.txt
    sudo dpkg -i task_linux_amd64.deb
script:
  - task build
