dist: bionic
sudo: false
addons:
  apt:
    packages:
      - python3
      - python3-pytest
      - jq
before_install:
  - |
    wget https://github.com/go-task/task/releases/download/v2.8.0/task_linux_amd64.deb > /tmp
    https://github.com/go-task/task/releases/download/v2.8.0/task_checksums.txt > /tmp
    sudo dpkg -i /tmp/task_linux_amd64.deb
script:
  - task build
