FROM        ubuntu:18.04 AS build

ENV         dumbinitver         1.2.5
ENV         dumbinitsha256      3eda470d8a4a89123f4516d26877a727c0945006c8830b7e3bad717a5f6efc4e

WORKDIR     /build

RUN         apt update && \
            apt install -y \
                wget \
                musl-tools \
                make && \
            wget https://github.com/Yelp/dumb-init/archive/v$dumbinitver.tar.gz && \
            echo "$dumbinitsha256 v$dumbinitver.tar.gz" > sha256sums && \
            sha256sum -c sha256sums && \
            tar xf v$dumbinitver.tar.gz && \
            cd dumb-init-$dumbinitver && \
            CC=musl-gcc make && \
            cp dumb-init /

FROM        ubuntu:16.04

LABEL       maintainer  "elcfd <elcfd@whitetree.xyz>"

ENV         LANG                en_US.UTF-8
ENV         DEBIAN_FRONTEND     noninteractive

RUN         apt-get update && \
            apt-get install -y \
                gawk \
                wget \
                git-core \
                diffstat \
                unzip \
                texinfo \
                gcc-multilib \
                build-essential \
                chrpath \
                socat \
                cpio \
                python \
                python3 \
                python3-pip \
                python3-pexpect \
                xz-utils  \
                debianutils \
                iputils-ping \
                python3-git \
                python3-jinja2 \
                libegl1-mesa \
                libsdl1.2-dev \
                pylint3 \
                locales \
                parted \
                dos2unix \
                ncurses-dev \
                tree \
                sudo \
                tmux \
                vim && \
                apt autoremove -y && \
            /usr/sbin/locale-gen en_US.UTF-8

COPY        --from=build /dumb-init /usr/bin/

COPY        scripts/bitbake-setup.py \
            scripts/bitbake-launch.sh \
            /usr/bin/

COPY        files/sudoers.usersetup /etc/

RUN         groupadd -g 70 usersetup && \
            useradd -N -m -u 70 -g 70 usersetup && \
            chmod 755 /usr/bin/bitbake-setup.py \
                      /usr/bin/bitbake-launch.sh \
                      /usr/bin/dumb-init && \
            echo "#include /etc/sudoers.usersetup" >> /etc/sudoers

USER        usersetup

ENTRYPOINT  ["/usr/bin/dumb-init", "--", "bitbake-setup.py"]
CMD         ["--workdir=/workdir"]
