FROM        ubuntu:18.04

LABEL       maintainer  "elcfd <elcfd@whitetree.xyz>"

ENV         LANG                en_US.UTF-8
ENV         DEBIAN_FRONTEND     noninteractive

RUN         apt update && \
            apt install -y \
                gawk \
                wget \
                git-core \
                diffstat \
                unzip \
                texinfo \
                gcc-multilib \
                build-essential \
                chrpath \
                socat \
                cpio \
                python \
                python3 \
                python3-pip \
                python3-pexpect \
                xz-utils  \
                debianutils \
                iputils-ping \
                python3-git \
                python3-jinja2 \
                libegl1-mesa \
                libsdl1.2-dev \
                pylint3 \
                locales \
                parted \
                dos2unix \
                ncurses-dev \
                tree \
                sudo \
                tmux \
                dumb-init \
                vim && \
                apt autoremove -y && \
            /usr/sbin/locale-gen en_US.UTF-8

COPY        scripts/bitbake-setup.py \
            scripts/bitbake-launch.sh \
            /usr/bin/

COPY        files/sudoers.usersetup /etc/

RUN         groupadd -g 70 usersetup && \
            useradd -N -m -u 70 -g 70 usersetup && \
            chmod 755 /usr/bin/bitbake-setup.py \
                      /usr/bin/bitbake-launch.sh && \
            echo "#include /etc/sudoers.usersetup" >> /etc/sudoers

USER        usersetup

ENTRYPOINT  ["/usr/bin/dumb-init", "--", "bitbake-setup.py"]
CMD         ["--workdir=/workdir"]
