version: '2'

silent: true

vars:
  IMAGES:

tasks:
  default:
    cmds:
      - task: build
      - task: tests
      - task: release

  build:
    cmds:
      - python3 image_creator.py build {{.IMAGES}}

  tests:
    cmds:
      # Temporary fix - should be a deps on build task
      - python3 image_creator.py build {{.IMAGES}}
      - python3 -m pytest -v --image_names {{.IMAGES}}

  release:
    cmds:
      - python3 image_creator.py release {{.IMAGES}}
