version: '2'

silent: true

vars:
  IMAGES: all

tasks:
  default:
    summary: Build, test and release the docker images
    cmds:
      - task: build
      - task: test
      - task: release

  build:
    summary: Build the docker images
    cmds:
      - python3 image_creator.py build {{.IMAGES}}

  test:
    summary: Run the unit test suite
    deps:
      - task: build
    cmds:
      - python3 -m pytest -v --image_names {{.IMAGES}}

  release:
    summary: Push the built images to Dockerhub
    cmds:
      - python3 image_creator.py release {{.IMAGES}}
