name: bitbake docker ci
on:
  push:
  schedule:
    - cron: '0 10 * * 5,6,0'

env:
  DOCKERHUB_USERNAME: elcfd

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
      fail-fast: false
    steps:
      - name: install taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true
      - name: install pip dependencies
        run: |
          python3 -m pip install -U pip
          pip install pytest
      - name: source code checkout
        uses: actions/checkout@v2
      - name: build and test
        run: task IMAGES=${{ matrix.image_name }} test
      - name: release
        if: contains(github.ref, 'release')
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          task IMAGES=${{ matrix.image_name }} release
